### ISSUE TITLE
You can create directed edges on undirected graphs which results in syntax errors in dot

### ISSUE THREAD

**Issue by drt24** [awalterschulze/gographviz#15]
Unless you call `graph.SetDir(true)` then calling `graph.AddEdge(parent, name, true, make(map[string]string))` will result in syntax errors like:

    Error: <stdin>: syntax error in line 2 near '->'

This should be documented on AddEdge.

**Comment by awalterschulze** [comment]
How would you propose to do that?

**Comment by drt24** [comment]
// If directed is set to true then SetDir(true) must also be called or there will be a syntax error in the output.

It would also be possible to produce a warning/panic/error in AddEdge `if directed && !this.Directed {` but that would change the API or be messy so documenting it is probably sufficient to avoid people making this mistake.

**Comment by awalterschulze** [comment]
Sounds good :)

**Comment by awalterschulze** [comment]
https://github.com/awalterschulze/gographviz/commit/ceec261a3df626c268a45365764d7622dd6816e6
