### ISSUE TITLE
Attributes of nodes are ignored when they are declared after their edges

### ISSUE THREAD

**Issue by nkitchen** [awalterschulze/gographviz#32]
I found an issue with the fix to #26: If an edge statement refers to a node, and then the statement for the node appears later with attributes, those attributes are ignored.

The man page for `dot` is arguably ambiguous on this, but its output clearly differs from gographviz.

I'll post an example as soon as I can.

**Comment by nkitchen** [comment]
Example input:
```
digraph g {
   rankdir=LR;
   node [shape=record, fillcolor=red, style=filled];
   A [shape=circle];
   A -> B;
   B [fillcolor=blue];
}
```
Rendered by `dot`:
![image](https://cloud.githubusercontent.com/assets/118448/26813482/5a2a3f1c-4a33-11e7-9457-357df7c7d70b.png)

Result from `gographviz.Read` and `Graph.String`:
```
digraph g {
        rankdir=LR;
        A->B;
        A [ fillcolor=red, shape=circle, style=filled ];
        B [ fillcolor=red, shape=record, style=filled ];

}
```
Note that B is not blue.

**Comment by awalterschulze** [comment]
Cool.   Well spotted again.

Next step would be to create a test, do you want to or should I?

**Comment by nkitchen** [comment]
I didn't get a test written within my available time today. I'm still willing to do it if you don't get to it first.

**Comment by awalterschulze** [comment]
I'll wait for you to write the test, unless you tell me differently.
This week is a little crazy.

**Comment by awalterschulze** [comment]
I believe you fixed this :)
Thanks again :)
