### ISSUE TITLE
not support goroutine safe

### ISSUE THREAD

**Issue by cloverstd** [awalterschulze/gographviz#38]
When I use it in concurrent, it will panic with 'concurrent map writes'.

**Comment by awalterschulze** [comment]
Which part, the parser?

**Comment by cloverstd** [comment]
My panic is here

https://github.com/awalterschulze/gographviz/blob/c45f112108a6f5c61d58ff3b66bfc0d0e5bef06d/relations.go#L34-L43

but I think that all the map in gographviz may be need lock for writing.

**Comment by awalterschulze** [comment]
If you want a reentrant graph I would create an implementation of
gographviz.Interface

https://github.com/awalterschulze/gographviz/blob/c45f112108a6f5c61d58ff3b66bfc0d0e5bef06d/gographviz.go#L29

Which has a mutex inside that protects every method.

**Comment by awalterschulze** [comment]
Closing this as there was an answer provided.
I hope that is okay.
