### ISSUE TITLE
How to get subtree based on parent node?

### ISSUE THREAD

**Issue by bbernhard** [awalterschulze/gographviz#39]
Hi, 

first of all, many thanks for the great library - it's really a pleasure to use!

I am currently evaluating gographviz for another project (https://github.com/bbernhard/imagemonkey-core) and would be glad if I could use it there. 

One thing I am currently struggling with is, the possibility to extract a subtree based on a given label. If I understood the documentation correctly, then that's what `SortedChildren` is meant to be for. However, for some obscure reason it doesn't seem to work - it looks like I have messed something up here. 

Here is a small code snippet which illustrates my problem. `truck`, `bike`, `motorbike` and `car` are all children of `vehicle`. When asking `gographviz` for the label `vehicle` I would like to get a list of all its children. I tried to accomplish that with `graph.Relations.SortedChildren("vehicle")` but that returns an empty list.  

I am pretty sure that I have missed something here and would be glad, if you could point me in the right direction. 

Thanks a lot,
Bernhard

```
package main

import (
	"bytes"
	"os"
	"fmt"
	"github.com/awalterschulze/gographviz"
)

func main() {
	graphAst, _ := gographviz.ParseString(`
		digraph G { 
			{ 
				car [label="car" id="94bbd2ff-8a8e-4d1c-9ac5-f9506aa20e43"] 
				vehicle [color=green style=filled label="vehicle"] 
				truck [label="truck"] 
			} 
			
		   vehicle -> truck
		    vehicle -> car
		    vehicle -> motorbike
		    vehicle -> bike
		}
	`)
	graph := gographviz.NewGraph()
	graph.SetDir(true)
	if err := gographviz.Analyse(graphAst, graph); err != nil {
    	panic(err)
	}

	childrens := graph.Relations.SortedChildren("vehicle")
	for _, child := range childrens {
		fmt.Printf("%s\n", child)
	}
}
```

**Comment by awalterschulze** [comment]
Hi Bernhard

No problem.
The Relations field is all about the relationships between graphs.  So the children being referred to here is the current graph's subgraphs.

In this case what you are looking for is the graph's Edges field.
You should be able to get the output you want with the following code:
```go
childrens := graph.Edges.SrcToDsts["vehicle"]
for _, child := range childrens {
     fmt.Printf("%s\n", child.Dst)
}
```

**Comment by awalterschulze** [comment]
If you do end up using this library, please let me know, so we can add you to the user's lists.

**Comment by bbernhard** [comment]
> No problem.
The Relations field is all about the relationships between graphs. So the children being referred to here is the current graph's subgraphs.

In this case what you are looking for is the graph's Edges field.
You should be able to get the output you want with the following code:

Awesome, thanks a lot for your help - works like a charm :)

As far as I have seen, this only returns the direct childen, right? Is there also the possibility to recursively get all the children from a given start node? 

Let's assume I have the following graphviz represenation: 

```
digraph G { 
	{ 
		car [label="car" id="94bbd2ff-8a8e-4d1c-9ac5-f9506aa20e43"] 
		vehicle [color=green style=filled label="vehicle"] 
		truck [label="truck"] 
		motorbike [label="motorbike"]
		bike [label="bike"]
		motorized [label="motorized"]
		nonmotorized [label="non-motorized"]
		scooter [label="scooter"]
	} 
	
	vehicle -> motorized
	vehicle -> nonmotorized
	motorized -> motorbike
	motorized -> truck
	motorized -> car
       nonmotorized -> bike
       nonmotorized -> scooter
}
```

When I query for `vehicle` I would like to get all it's children (i.e `motorized`, `nonmotorized`, `motorbike`, `car`, `truck`, `bike`, `scooter`) instead of just its direct children (`motorized`, `nonmotorized`). 


I extended the code snippet from you to recursively get all the children: 

```
func findAllChildren(graph *gographviz.Graph, label string) []string {
	var result []string

	var labels []string
	labels = append(labels, label)

	var innerFct func(graph *gographviz.Graph, labels []string)

	innerFct = func(graph *gographviz.Graph, labels []string) {

		if(len(labels) == 0) {
			return
		}

		//remove first element from list
		label := labels[0]
		labels = append(labels[:0], labels[1:]...)

		childrens := graph.Edges.SrcToDsts[label]
		for _, child := range childrens {
		    for _,c := range child {
		    	labels = append(labels, c.Dst)
		    	result = append(result, c.Dst)
		    }
		}

		innerFct(graph, labels)
	}

	
	innerFct(graph, labels)

	return result
}
```

While it seems to work, I am not sure if this is the best way to accomplish this or if there are already some methods built-in which could help me with that? I don't know if your library has any limitations regarding size, but in the end I would aim for graphs with at least 1000 nodes. :)

Many thanks for your help - really appreciated!

> If you do end up using this library, please let me know, so we can add you to the user's lists.

Awesome, will definitely do!

**Comment by bbernhard** [comment]
fyi, I did a quick performance test: 

10000 nodes: ~10ms (recursively finding all children)
30000 nodes: ~65ms (recursively finding all children)

I am pretty sure my implementation is not the fastest..so there is for sure room for improvement. But nevertheless, those numbers already look pretty good.

(I'll still monitor this thread in case there is already a built-in method for that - in that case I would replace my solution with a proper one. But in case there isn't one, it's also not a big deal; my hacky solution performs well enough for now)

I really like gographviz so far, so I'll definitely give it a try. Many thanks again for your help, Walter! 

Have a nice day,
Bernhard

**Comment by awalterschulze** [comment]
Yes for this you will need to traverse the graph.
gographviz is just a parser and does not provide any helper functions, or at least tries not to.

I would add a map to track which nodes I have already visited.
And maybe you already have, but I would study the append, since allocating memory would be the expensive part of this algorithm.

Another option:
gographviz also provides an interface, which allows you to parse directly into your own structure or go from the gograpviz ast to your own structure.
This should allow you to parse directly into an optimized structure or into the appropriate structure with helper functions provided by another library.

**Comment by bbernhard** [comment]
> Yes for this you will need to traverse the graph.
gographviz is just a parser and does not provide any helper functions, or at least tries not to.

I would add a map to track which nodes I have already visited.
And maybe you already have, but I would study the append, since allocating memory would be the expensive part of this algorithm.

Another option:
gographviz also provides an interface, which allows you to parse directly into your own structure or go from the gograpviz ast to your own structure.
This should allow you to parse directly into an optimized structure or into the appropriate structure with helper functions provided by another library.

Many thanks for the useful tips - will definitely implement them!

> I think we can close this issue?

Yeah, right. Many thanks for your help, Walter. Your library works like a charm - will definitely use it. :)
