### ISSUE TITLE
Expose DOT-specific keywords

### ISSUE THREAD

**Issue by kargakis** [awalterschulze/gographviz#4]
A user shouldn't manually construct DOT keywords before adding them in the attributes of a graph object. All the names mentioned in [here](http://www.graphviz.org/doc/info/attrs.html#a:charset) should be exposed by this package.

**Comment by awalterschulze** [comment]
I agree, it would be safer to have all the attributes so stringly typed.

We could make type safe and constrained methods to build the map[string]string and not break the current API. 

This is quite a long list of things to implement and, unfortunately, I am currently very busy, but I would be open to contribution.
I am very sorry and I hope that this is an acceptable answer?

**Comment by kargakis** [comment]
Thanks for the answer! No worries, it's good that you agree about the issue. I might submit a PR if time permits it.:)

**Comment by awalterschulze** [comment]
I look forward to it :)

**Comment by awalterschulze** [comment]
I have decided that we are going to make a breaking change to return some errors.
Or at least that is what this proposal is about
https://github.com/awalterschulze/gographviz/issues/23
Hopefully we can then fix this keyword problem as well.

**Comment by awalterschulze** [comment]
Merged pull request https://github.com/awalterschulze/gographviz/pull/25 with some attribute validation.
