### ISSUE TITLE
gographviz in production - a short review

### ISSUE THREAD

**Issue by bbernhard** [awalterschulze/gographviz#40]
Hi,

just wanted to let you know, that we are using gographviz in production for now almost two weeks. It's really a pleasure to work with the library - the API is intuitive and nicely documented and the library is stable. Awesome work!

## What are we using gographviz for?
Currently we use the the library to build up a interactive label graph for our public image dataset. gographviz parses our label graph dot file and creates the nodes and edge information which will be rendered with d3.js. In case you want to have a look: https://imagemonkey.io/graph

There is also a online label graph editor (https://imagemonkey.io/graph?editor=true) which uses gographviz to parse and validate the input. 

![label_graph_editor](https://user-images.githubusercontent.com/5710631/41051523-abe384be-69b6-11e8-82fd-8ef71bff322e.gif)

I hope it's okay to post that here, as it's not really a bug. You can close that issue...just wanted to let you know that are successfully using your library. ;-)

Have a nice day,
Bernhard

**Comment by awalterschulze** [comment]
Wow that looks really cool.  I'll add you to the readme as a user.

There does seem to be an error when I visited the page, seems like something that should be a quick fix.

<img width="729" alt="screen shot 2018-06-07 at 6 47 16 am" src="https://user-images.githubusercontent.com/1829933/41078734-cbc2eb72-6a1e-11e8-81b6-4074720101fb.png">

**Comment by awalterschulze** [comment]
Creating an issue here, was a perfect way to let me know.

How did you add the code completion to the text editor?

**Comment by bbernhard** [comment]
> Wow that looks really cool. I'll add you to the readme as a user.

Awesome, thanks!

> There does seem to be an error when I visited the page, seems like something that should be a quick fix.

Oops, looks like that I forgot to change the URL of the script so that it gets served from my own server. Many thanks for the info! 

> How did you add the code completion to the text editor?

Fortunately [ace.js](https://ace.c9.io/) supports dot files out of the box. So it's basically just that line needed to makes ace.js aware that it's a dot file: `editor.getSession().setMode("ace/mode/dot");` 

The only thing that ace.js is missing is a live syntax checker for dot files (would be kinda cool to get live visual feedback if you make a syntax error. (ace.js has a few live syntax checkers for other languages, but nobody implemented one for the dot language. But they have a well defined interface for that, so it's possible to write own live syntax checkers)

**Comment by awalterschulze** [comment]
Ah cool.  Thanks for sharing :)

**Comment by awalterschulze** [comment]
This is added to the readme, so closing this as it is not an issue.
But still really great to hear about use cases, thank you so much for sharing <3
