### ISSUE TITLE
Dead links for documentation

### ISSUE THREAD

**Issue by jhollowayj** [awalterschulze/gographviz#42]
I was reading through the [source code about attributes](https://github.com/awalterschulze/gographviz/blob/49969fe6eded40a16118a63c7742990e5808308e/attr.go#L32) and found some URLs to GraphViz's webpage that are now dead.  It looks like they have migrated.  I don't have time right now to do a PR, but here's the new url:

```go
/* Old */
// Damping http://www.graphviz.org/content/attrs#dDamping

/* New */
// Damping http://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:Damping
```

Hope that helps a little bit.  :)  Thanks for the work you've already done!  Super helpful!

**Comment by awalterschulze** [comment]
Thank you so much for reporting :)

**Comment by awalterschulze** [comment]
fixed https://github.com/awalterschulze/gographviz/commit/16ed621cdb519d1179e1e8c741abcdc0f263377f
