### ISSUE TITLE
ast.NewSubGraph data race due to rand.NewSource

### ISSUE THREAD

**Issue by temoto** [awalterschulze/gographviz#46]
Hello.

Thank you very much for great library. I try to use dot as storage format for user defined graphs.

Found this with parallel tests:

https://github.com/awalterschulze/gographviz/blob/da5c847b6fb13f2f76225f0ca9d912f5801d92e7/ast/ast.go#L187

produces data race in `math/rand.(*Rand).Int63()` because you create new rand source in 

https://github.com/awalterschulze/gographviz/blob/da5c847b6fb13f2f76225f0ca9d912f5801d92e7/ast/ast.go#L29

which is not thread-safe, as docs say:

> https://golang.org/pkg/math/rand/#NewSource
> Unlike the default Source used by top-level functions, this source is not safe for concurrent use by multiple goroutines.

I can imagine you had best intentions for fast or reproducible PRNG. Maybe what was required for testing leaked into production code. I'm not sure how to fix this without breaking API.

IMHO this could be a start:

```
func NewSubGraph(id, l Attrib) (*SubGraph, error) {
	g := &SubGraph{}
	if id == nil {
		g.ID = ID(fmt.Sprintf("anon%d", r.Int63()))
	} else if len(id.(ID)) > 0 {
		g.ID = id.(ID)
	}
	if l != nil {
		g.StmtList = l.(StmtList)
	}
	return g, nil
}
```

So "anon%d" generation could be moved into (hopefully stateful) `ProdTabEntry`.

It also removes unconditional allocation to relax GC worried people.

Of course, just using thread-safe `rand.Int63()` function fixes data race.

What you think?

**Comment by awalterschulze** [comment]
Hi sorry for the delay, I have been sick.

Thanks for the compliment :)

You are right on two counts.
Yes I wanted a reproducible parse for testing.
And yes moving that allocation into the if is a great idea.

Maybe we could also create some sort of locked source of our own to solve this problem
https://golang.org/src/math/rand/rand.go?s=10197:10223#L288
What do you think?

**Comment by temoto** [comment]
I think power of `rand.NewSource` is in speed. If you're fine with sub-optimal speed :-) then `math/rand.Int63()` should work. I wanted to see how setting custom rand seed would fit into testing suite but failed to provoke "anon%d" mismatch failure with just `make regenerate` and `go test ./...`

Is it possible you also run checks in a different way?

**Comment by awalterschulze** [comment]
I believe this was fixed by the linked pull request.
Thanks again :D
