### ISSUE TITLE
Quote node IDs and attributes

### ISSUE THREAD

**Issue by joshk0** [awalterschulze/gographviz#5]
Hi there, thanks for this package.

My node IDs and attribute values disagree strongly with the DOT schema, and I've found that I have to quote them in order for tools like Gephi to parse them as they all are of type "ID".

Could gographviz detect the need to quote/escape anything that it needs to write out as type ID and do so automatically so I don't have to add the quotes myself? Here's an example that produces an unreadable file:

```
graph := gographviz.NewGraph()
graph.SetName("G")
graph.AddNode("G", "331fb1985e8884cfaaae65be7f8cfe5b", gographviz.Attrs{"label": "1:6:1w/w/PYqH7d1+6Fg"})
graph.AddEdge("331fb1985e8884cfaaae65be7f8cfe5b", "ec2f3d34a4f4c4f82dd1d0b2f1a581e", gographviz.Attrs{"label": "FOO_BAR"})
os.Stdout.Write(gographviz.WriteAst().String())
```

Thanks!

**Comment by awalterschulze** [comment]
Have you tried?

```
gographviz.NewEscape() 
```
Instead of
```
gographviz.NewGraph()
```

**Comment by awalterschulze** [comment]
If this does not work please reopen the issue.

**Comment by joshk0** [comment]
Thanks, that works, though there are fewer functions in that interface. Would be nice to have IsNode()

**Comment by awalterschulze** [comment]
Would you like to submit a pull request or I can add this?

**Comment by joshk0** [comment]
If you've got it in stock, go nuts. If not, turn this into an issue and i can poke at it. Shoudln't be too hard, i think.

**Comment by awalterschulze** [comment]
IsNode is now a method on Escape :)

**Comment by joshk0** [comment]
Thank you!

**Comment by awalterschulze** [comment]
No problem, may I ask for which project you are using gographviz, so that I may extend my user list?
