### ISSUE TITLE
Escape graph is not intuitive

### ISSUE THREAD

**Issue by willis7** [awalterschulze/gographviz#50]
I only stumbled on this feature because of #10 .

Whilst I understand the rationale, I think it makes the API a little untidy to have a second struct type. As this is a failure case with the dot tool, is it worth escaping as default?

**Comment by willis7** [comment]
I still love this library though, kudos!

**Comment by awalterschulze** [comment]
Hard to make it default in hindsight though :(
Maybe it would be nice to add it to the Readme.md?

**Comment by willis7** [comment]
Sure, I will make a PR to support.

**Comment by awalterschulze** [comment]
I am going to close this, but feel free to reopen, when you have time.
