### ISSUE TITLE
Make it a full-functionality Graphviz API for Go

### ISSUE THREAD

**Issue by hsluoyz** [awalterschulze/gographviz#56]
This project currently only focuses on DOT manipulation. But I believe many users need a full API for Graphviz in Go, like the rendering, layout, etc. Similar to Python: https://graphviz.readthedocs.io

The name of this package is `gographviz`, so it should be a full API wrapper for Graphviz. Can you support it? Thanks.

**Comment by awalterschulze** [comment]
I would love to have that support.  Pull Requests are welcome, but I don't currently have time to build it sorry.

**Comment by awalterschulze** [comment]
Happy for someone to do this, but they can then reopen this issue or create their own, since that would be a huge project.
Going to close this for now.
