### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by utkarsh2102** [awalterschulze/gographviz#57]
Hi,

There have been 27 commits since the last release, perhaps time for another release? :)

**Comment by awalterschulze** [comment]
version 2.0.1 has been released

Thank you for reporting :)

**Comment by awalterschulze** [comment]
version 2.0.1 is broken

**Comment by awalterschulze** [comment]
Although I can't reproduce the failure locally :(

**Comment by utkarsh2102** [comment]
@awalterschulze, eeks, no worries.
I can help you with that bit ;)

**Comment by awalterschulze** [comment]
That would be great.
Also probably should move over to github actions
https://github.com/awalterschulze/gographviz/issues/58
Might be an easier fix

**Comment by awalterschulze** [comment]
Got the same error on master
https://travis-ci.org/github/awalterschulze/gographviz/builds/671231771?utm_medium=notification&utm_source=email

But locally I don't get this and I have upgraded to go version 14

**Comment by utkarsh2102** [comment]
Hi @awalterschulze,
I am using Golang 1.14 and I can't seem to reproduce any failure either.
I built this module in a clean chroot (clean environment) and this seemed to build fine with all tests passing.

**Comment by awalterschulze** [comment]
Awesome, thank you for confirming :)
Then I think this issue now depends on switching to github actions: #58

**Comment by utkarsh2102** [comment]
Right, so if you need help in reproducing or something, I'll be a ping away ;)
I'd have helped with #58, definitely, but I've got zero experience in that :/

Furthermore, I also built `aptly` against 2.0.1 version and things seemed fine. So I don't think it is much of a problem :)

**Comment by awalterschulze** [comment]
Cool, great to hear.

I'll wait for someone with XP or anyone willing to learn.

I am also a bit busy right now.

**Comment by awalterschulze** [comment]
github action has been implemented thanks to @jmrtt
So I made another release version 2.0.2

I think maybe now we can close this issue, since it is easy to make new releases in future.
Feel free to still comment on this issue.

**Comment by utkarsh2102** [comment]
This is great, thanks @awalterschulze and @jmrtt! ❤️
