### ISSUE TITLE
setup github action

### ISSUE THREAD

**Issue by awalterschulze** [awalterschulze/gographviz#58]
Would love to replace travis job with github action, if anyone is interested in helping?

**Comment by jmrtt** [comment]
I would like to help. Created PR #66 that replaces travis job with github action and executes the same steps. Please let me know if that was the idea, or you would like to add/change something else.

**Comment by awalterschulze** [comment]
Thank you.  Yes you are totally on the right path :D

**Comment by awalterschulze** [comment]
I think you fixed this :)
Thanks again
