### ISSUE TITLE
How to implement an anonymous subgraph

### ISSUE THREAD

**Issue by csghuser** [awalterschulze/gographviz#59]
Hello, many thanks for this library!

I have a question which is duplicate of this issue here:

https://github.com/awalterschulze/gographviz/issues/9#issue-118955052

In a manual graphviz chart I have the following setup. 

At the top of my graph I have defined:

```
  newrank=true;
```

As part of my graph I have the following anonymous graph:

```
{ rank=same; some_node_1; some_node_2; }  # How to inject this line?
```

This works, however similar to the issue linked above, how do I accomplish this in gographviz?

**Comment by awalterschulze** [comment]
Could you try parsing it with gographviz and reverse engineering it that way?
Please let me know what you find, so that I can try to help.

**Comment by csghuser** [comment]
I managed to get an example of this working, before and after the changes. 

The graph for this example has been borrowed from https://stackoverflow.com/q/6824431
Also the answer as well 🙂 

```
g, _ := gographviz.Read([]byte(`digraph G {
    subgraph cluster1 {
        label="Local Datacenter";
        router1;
        host1;
    }
    subgraph cluster2 {
        label="Remote Datacenter";
        router2;
        host2;
    }
    router1 -> router2;
    router2 -> host2;
    router1 -> host1;
}`))
s := g.String()
fmt.Println(s)
```

This produces the following:

![image](https://user-images.githubusercontent.com/9674019/85159074-e9ef6a00-b254-11ea-9242-5b13676ca792.png)

Where as we want them on the same level, so..... we add the following section to the code above:

```
g.AddAttr("G", "newrank", "true")
g.AddSubGraph("G", "force_node_same_level", map[string]string{"rank": "same"})
g.AddNode("force_node_same_level", "router1", nil)
g.AddNode("force_node_same_level", "router2", nil)
s := g.String()
fmt.Println(s)
```

Which gives us:

![image](https://user-images.githubusercontent.com/9674019/85159279-33d85000-b255-11ea-9d08-b344e17ecb27.png)


I was struggling to work out out to add the subgraph above but it's actually fairly straightforward. Hopefully this helps someone else! 🙂

**Comment by awalterschulze** [comment]
Thank you so much.
This is SUPER helpful.
I really appreciate the effort of not only finding the answer, but documenting it so well for others (including me).
Great job.

**Comment by awalterschulze** [comment]
I am closing the issue, but I also added a link to this issue from the Readme, to make it easier for other users to find.
