### ISSUE TITLE
Cluster getting included as a node

### ISSUE THREAD

**Issue by sandlerben** [awalterschulze/gographviz#6]
I am trying to generate a graph from [this](https://www.dropbox.com/s/s1qe1pvtu6lk9g9/dotout.dot?dl=0) dot file. Here is the code I have right now:

    graphAst, error := parser.ParseBytes(dotText)
    dag := ggv.NewGraph()
    ggv.Analyse(graphAst, dag)

dag.Nodes includes a Node called `L` even though there is no node `L` in the .dot input. I suspect that there is a bug where the `cluster_L` cluster is being parsed as a node.

**Comment by awalterschulze** [comment]
Here is Node L
```
L [shape=box fontsize=32 label="Type: cpu\lTime: Jun 29, 2015 at 10:50pm (UTC)\lDuration: 5s\l4040ms of 4040ms total (  100%)\l"] 
```
And cluster_L is stored in Subgraphs.

**Comment by awalterschulze** [comment]
If I misunderstood please reopen the issue.
