### ISSUE TITLE
escaping rules, Is period escaped?

### ISSUE THREAD

**Issue by slangens1** [awalterschulze/gographviz#60]
are periods escaped using the escape API?

given the following code https://play.golang.org/p/G_8QqcEn9yO i'd expect these nodes to be escaped. Running them through dot causes a syntax error.
<pre>
sig@desktop2:~$ dot -Tsvg graph.dot 
Error: graph.dot: syntax error in line 3 near '.'
sig@desktop2:~$ dot -Tsvg graph.dot ^C
sig@desktop2:~$ cat graph.dot 

digraph G {
        a.b->a.c;
        a.b;
        a.c;
}
</pre>

used the following code from playground to generate the graph
<pre>
package main

import (
	"fmt"
	graph "github.com/awalterschulze/gographviz"
)

func main() {
n := "G"
	g := graph.NewEscape()
	g.SetDir(true)
	g.SetName(n)
	g.AddNode(n, "a.b", nil)
	g.AddNode(n, "a.c", nil)
	g.AddEdge("a.b", "a.c", true, nil)
	fmt.Printf("%s\n", g.String())
}
</pre>

**Comment by awalterschulze** [comment]
Good catch.  I agree this is a bug.
How do you feel about adding escaping in a pull request?

**Comment by awalterschulze** [comment]
I believe this has now been fixed https://github.com/awalterschulze/gographviz/pull/65
Thank you @jmrtt
