### ISSUE TITLE
Gographviz shown as an incompatible package when imported

### ISSUE THREAD

**Issue by ZhangYW18** [awalterschulze/gographviz#63]
I'm using Gographviz in our project, and Gographviz is shown as an incompatible package in go.mod:

```go
	github.com/awalterschulze/gographviz v2.0.1+incompatible
```

It's because Gographviz has not opted in to `go modules` but has been tagged with v2+ SemVer tags.

It would be better if Gographviz starts to use `go modules` to manage its dependencies, which is recommended by Golang officials.

**Comment by awalterschulze** [comment]
No idea how `go modules` work, but happy to accept a pull request that makes it easier for other people to use gographviz, with their dependency manager of choice.
`gographviz` has no dependencies outside of the go standard library and a code generator `gocc`, so I hope this makes it easy.
