### ISSUE TITLE
Build is failing due to changes in Github Actions

### ISSUE THREAD

**Issue by jmrtt** [awalterschulze/gographviz#75]
Build is currently failing with the following error:
![image](https://user-images.githubusercontent.com/2771025/125596019-7e699586-bb9a-4e07-b498-e92fd69ff211.png)

This is happening since Github Actions deprecated `set-env` and `add-path` commands and now we should use environment files.

For more details see:
* https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files

**Comment by jmrtt** [comment]
Created PR #76 to solve this issue and update the generated files.

**Comment by awalterschulze** [comment]
I believe this is fixed now, great job :D
