### ISSUE TITLE
[Question] How to delete Edges properly?

### ISSUE THREAD

**Issue by phandox** [awalterschulze/gographviz#79]
Hi,

I have loaded graph from DOT file and would like to remove Edge from the graph. I implement [Kahn's algorithm ](https://en.wikipedia.org/wiki/Topological_sorting) for topological sorting and it requires removing edges from graph.

I understand that I can probably delete element from maps `Graph.Edges.DstToSrcs` and `Graph.Edges.SrcToDsts` but I wonder if it's not more involved so that graph stays valid.

Thanks for pointers!

**Comment by awalterschulze** [comment]
If you implement this interface

```
type Interface interface {
	SetStrict(strict bool) error
	SetDir(directed bool) error
	SetName(name string) error
	AddPortEdge(src, srcPort, dst, dstPort string, directed bool, attrs map[string]string) error
	AddEdge(src, dst string, directed bool, attrs map[string]string) error
	AddNode(parentGraph string, name string, attrs map[string]string) error
	AddAttr(parentGraph string, field, value string) error
	AddSubGraph(parentGraph string, name string, attrs map[string]string) error
	String() string
}
```

Then the parser can parse into your graph data structure, where you can also implement deletion etc.

The idea of this package is to only implement the parser and unfortunately not to also be the data structure that works for all algorithms. I am sorry
