### ISSUE TITLE
How to Use {rank=same;node1,node2}

### ISSUE THREAD

**Issue by VnlyZhang** [awalterschulze/gographviz#9]
HI,
    I really appreciate your work on graphviz,Now it's confused to use rank,please help me,thks very much!

**Comment by awalterschulze** [comment]
My pleasure :)
```
digraph ranksame {
	 {rank=same;node1 node2;}
}
```
parses to
```
digraph ranksame {
	subgraph anon2041104533947223744 {
		rank=same;
		node1;
		node2;
	};
}
```
Which means the curly braces create an anonymous subgraph.
Maybe I don't understand your question?

**Comment by awalterschulze** [comment]
No reply
